/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as ReaderRouteImport } from './routes/reader'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReaderIndexRouteImport } from './routes/reader/index'
import { Route as ReaderSettingsRouteImport } from './routes/reader/settings'
import { Route as ReaderSettingsIntegrationsRouteImport } from './routes/reader/settings/integrations'
import { Route as ReaderSettingsFeedsRouteImport } from './routes/reader/settings/feeds'
import { Route as ReaderSettingsAccountRouteImport } from './routes/reader/settings/account'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const ReaderRoute = ReaderRouteImport.update({
  id: '/reader',
  path: '/reader',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReaderIndexRoute = ReaderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReaderRoute,
} as any)
const ReaderSettingsRoute = ReaderSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ReaderRoute,
} as any)
const ReaderSettingsIntegrationsRoute =
  ReaderSettingsIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => ReaderSettingsRoute,
  } as any)
const ReaderSettingsFeedsRoute = ReaderSettingsFeedsRouteImport.update({
  id: '/feeds',
  path: '/feeds',
  getParentRoute: () => ReaderSettingsRoute,
} as any)
const ReaderSettingsAccountRoute = ReaderSettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => ReaderSettingsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reader': typeof ReaderRouteWithChildren
  '/sign-up': typeof SignUpRoute
  '/reader/settings': typeof ReaderSettingsRouteWithChildren
  '/reader/': typeof ReaderIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/reader/settings/account': typeof ReaderSettingsAccountRoute
  '/reader/settings/feeds': typeof ReaderSettingsFeedsRoute
  '/reader/settings/integrations': typeof ReaderSettingsIntegrationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sign-up': typeof SignUpRoute
  '/reader/settings': typeof ReaderSettingsRouteWithChildren
  '/reader': typeof ReaderIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/reader/settings/account': typeof ReaderSettingsAccountRoute
  '/reader/settings/feeds': typeof ReaderSettingsFeedsRoute
  '/reader/settings/integrations': typeof ReaderSettingsIntegrationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reader': typeof ReaderRouteWithChildren
  '/sign-up': typeof SignUpRoute
  '/reader/settings': typeof ReaderSettingsRouteWithChildren
  '/reader/': typeof ReaderIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/reader/settings/account': typeof ReaderSettingsAccountRoute
  '/reader/settings/feeds': typeof ReaderSettingsFeedsRoute
  '/reader/settings/integrations': typeof ReaderSettingsIntegrationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reader'
    | '/sign-up'
    | '/reader/settings'
    | '/reader/'
    | '/api/auth/$'
    | '/reader/settings/account'
    | '/reader/settings/feeds'
    | '/reader/settings/integrations'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/sign-up'
    | '/reader/settings'
    | '/reader'
    | '/api/auth/$'
    | '/reader/settings/account'
    | '/reader/settings/feeds'
    | '/reader/settings/integrations'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/reader'
    | '/sign-up'
    | '/reader/settings'
    | '/reader/'
    | '/api/auth/$'
    | '/reader/settings/account'
    | '/reader/settings/feeds'
    | '/reader/settings/integrations'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ReaderRoute: typeof ReaderRouteWithChildren
  SignUpRoute: typeof SignUpRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reader': {
      id: '/reader'
      path: '/reader'
      fullPath: '/reader'
      preLoaderRoute: typeof ReaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reader/': {
      id: '/reader/'
      path: '/'
      fullPath: '/reader/'
      preLoaderRoute: typeof ReaderIndexRouteImport
      parentRoute: typeof ReaderRoute
    }
    '/reader/settings': {
      id: '/reader/settings'
      path: '/settings'
      fullPath: '/reader/settings'
      preLoaderRoute: typeof ReaderSettingsRouteImport
      parentRoute: typeof ReaderRoute
    }
    '/reader/settings/integrations': {
      id: '/reader/settings/integrations'
      path: '/integrations'
      fullPath: '/reader/settings/integrations'
      preLoaderRoute: typeof ReaderSettingsIntegrationsRouteImport
      parentRoute: typeof ReaderSettingsRoute
    }
    '/reader/settings/feeds': {
      id: '/reader/settings/feeds'
      path: '/feeds'
      fullPath: '/reader/settings/feeds'
      preLoaderRoute: typeof ReaderSettingsFeedsRouteImport
      parentRoute: typeof ReaderSettingsRoute
    }
    '/reader/settings/account': {
      id: '/reader/settings/account'
      path: '/account'
      fullPath: '/reader/settings/account'
      preLoaderRoute: typeof ReaderSettingsAccountRouteImport
      parentRoute: typeof ReaderSettingsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ReaderSettingsRouteChildren {
  ReaderSettingsAccountRoute: typeof ReaderSettingsAccountRoute
  ReaderSettingsFeedsRoute: typeof ReaderSettingsFeedsRoute
  ReaderSettingsIntegrationsRoute: typeof ReaderSettingsIntegrationsRoute
}

const ReaderSettingsRouteChildren: ReaderSettingsRouteChildren = {
  ReaderSettingsAccountRoute: ReaderSettingsAccountRoute,
  ReaderSettingsFeedsRoute: ReaderSettingsFeedsRoute,
  ReaderSettingsIntegrationsRoute: ReaderSettingsIntegrationsRoute,
}

const ReaderSettingsRouteWithChildren = ReaderSettingsRoute._addFileChildren(
  ReaderSettingsRouteChildren,
)

interface ReaderRouteChildren {
  ReaderSettingsRoute: typeof ReaderSettingsRouteWithChildren
  ReaderIndexRoute: typeof ReaderIndexRoute
}

const ReaderRouteChildren: ReaderRouteChildren = {
  ReaderSettingsRoute: ReaderSettingsRouteWithChildren,
  ReaderIndexRoute: ReaderIndexRoute,
}

const ReaderRouteWithChildren =
  ReaderRoute._addFileChildren(ReaderRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ReaderRoute: ReaderRouteWithChildren,
  SignUpRoute: SignUpRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
